name: core_ui
description: core_ui
version: 0.0.1
homepage:
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  domain:
    path: ../domain
  home:
    path: ../features/home
  navigation:
    path: ../navigation
  readmore: ^2.2.0
  easy_localization: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
