name: core_ui
description: core_ui
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  domain:
    path: ../domain
  home:
    path: ../features/home
  cart:
    path: ../features/cart
  navigation:
    path: ../navigation
  cached_network_image: ^3.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
