name: food_delivery
description: food_delivery
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ./core
  core_ui:
    path: ./core_ui
  navigation:
    path: ./navigation
  home:
    path: ./features/home
  settings:
    path: ./features/settings
  cart:
    path: ./features/cart
  auth:
    path: ./features/auth
  order_history:
    path: ./features/order_history
  admin_panel:
    path: ./features/admin_panel
  domain:
    path: ./domain
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/translations/
    - assets/image/poland.png
    - assets/image/united-states.png
    - assets/image/onboarding_image.png
    - assets/image/checked.png
    - assets/image/empty_cart.png
    - assets/image/empty_order_history.png
    - assets/rive/wave.riv
    - assets/rive/font_size_12.riv
    - assets/rive/font_size_14.riv
    - assets/rive/font_size_16.riv
    - assets/rive/font_size_18.riv
    - assets/rive/font_size_20.riv
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-Black.ttf
          weight: 900
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/RobotoCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/RobotoCondensed-Italic.ttf
          style: italic
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Regular.ttf
        - asset: assets/fonts/Mulish-Medium.ttf
          weight: 500
        - asset: assets/fonts/Mulish-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Mulish-Bold.ttf
          weight: 700
        - asset: assets/fonts/Mulish-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Mulish-Black.ttf
          weight: 900        
