name: core
description: core
version: 0.0.1
homepage:
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  data:
    path: ../data
  domain:
    path: ../domain
  navigation:
    path: ../navigation
  core_ui:
    path: ../core_ui
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.1
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
